# Generated by Django 5.0 on 2023-12-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_dept',
            field=models.BooleanField(default=False),
        ),
    ]
