# Generated by Django 5.0 on 2023-12-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferapp', '0002_employee_has_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='has_dept',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='transferapp.department', to_field='dept_name'),
        ),
    ]
